- name: Deploy Elasticsearch
  hosts: elasticsearch_nodes
  become: true
  roles:
    - elasticsearch

- name: Deploy Kibana
  hosts: kibana_nodes
  become: true
  roles:
    - kibana

- name: Deploy certificate
  hosts: elasticsearch_nodes
  become: true
  roles:
    - certificates

- name: Deploy certificate
  hosts: elasticsearch_nodes
  become: true
  roles:
    - fleet-end-to-end