- name: Install dependencies
  apt:
    name: ['apt-transport-https', 'wget', 'gnupg']
    state: present
    update_cache: yes

- name: Add Elastic GPG key
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /etc/apt/keyrings/elastic.gpg
  args:
    creates: /etc/apt/keyrings/elastic.gpg

- name: Add Kibana APT repo
  copy:
    content: |
      deb [signed-by=/etc/apt/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/{{ kibana_major_version }}.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic.list

- name: Install Kibana
  apt:
    name: kibana={{ kibana_version }}
    state: present
    update_cache: yes

- name: Configure kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0640

- name: Enable and start Kibana
  systemd:
    name: kibana
    enabled: yes
    state: started
