---
- name: Install dependencies
  apt:
    name: ['apt-transport-https', 'wget', 'gnupg', 'openssl']
    state: present
    update_cache: yes

- name: Create apt keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Elasticsearch GPG key
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /etc/apt/keyrings/elasticsearch.gpg
  args:
    creates: /etc/apt/keyrings/elasticsearch.gpg

- name: Add Elasticsearch APT repo
  copy:
    content: |
      deb [signed-by=/etc/apt/keyrings/elasticsearch.gpg] https://artifacts.elastic.co/packages/{{ es_major_version }}.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic.list

# - name: Update apt cache immediately
#   apt:
#     update_cache: yes
#     cache_valid_time: 60

# - name: Install Elasticsearch
#   apt:
#     name: "elasticsearch={{ es_version }}"
#     state: present


- name: Manually install Elasticsearch (as a workaround)
  shell: |
    apt-get update && apt-get install -y elasticsearch={{ es_version }}
  args:
    executable: /bin/bash
  environment:
    DEBIAN_FRONTEND: noninteractive

# === Directory Setup ===
- name: Create data directory
  file:
    path: "{{ es_data_dir | default('/var/lib/elasticsearch') }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'

- name: Create logs directory
  file:
    path: "{{ es_log_dir | default('/var/log/elasticsearch') }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'


- name: Set JVM heap size
  blockinfile:
    path: /etc/elasticsearch/jvm.options.d/heap.options
    create: yes
    block: |
      -Xms{{ es_heap_size }}
      -Xmx{{ es_heap_size }}

- name: Ensure IP and hostname entry exists in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].node_name | default(item) }}"
    state: present
  loop: "{{ groups['elasticsearch_nodes'] }}"
  
