- name: Install dependencies
  apt:
    name: ['apt-transport-https', 'wget', 'gnupg']
    state: present
    update_cache: yes

- name: Create apt keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Elasticsearch GPG key
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /etc/apt/keyrings/elasticsearch.gpg
  args:
    creates: /etc/apt/keyrings/elasticsearch.gpg

- name: Add Elasticsearch APT repo
  copy:
    content: |
      deb [signed-by=/etc/apt/keyrings/elasticsearch.gpg] https://artifacts.elastic.co/packages/{{ es_major_version }}.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic.list

- name: Update apt cache immediately
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Elasticsearch
  apt:
    name: "elasticsearch={{ es_version }}"
    state: present

# === Directory Setup ===

- name: Create data directory
  file:
    path: "{{ es_data_dir | default('/var/lib/elasticsearch') }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'

- name: Create logs directory
  file:
    path: "{{ es_log_dir | default('/var/log/elasticsearch') }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'

# === Configuration ===

- name: Configure elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'

- name: Set JVM heap size
  blockinfile:
    path: /etc/elasticsearch/jvm.options.d/heap.options
    create: yes
    block: |
      -Xms{{ es_heap_size }}
      -Xmx{{ es_heap_size }}

# === Service ===

- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    enabled: true
    state: restarted
    daemon_reload: yes

- name: Reset elastic password
  command: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic --batch --url https://localhost:9200"
  register: elastic_pass_output
  become: true
  changed_when: "'password:' in elastic_pass_output.stdout"

- name: Show elastic password
  debug:
    msg: "{{ elastic_pass_output.stdout }}"
  when: "'password:' in elastic_pass_output.stdout"


- name: Reset kibana_system password
  command: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system --batch --url https://localhost:9200"
  register: kibana_pass_output
  become: true
  changed_when: "'password:' in kibana_pass_output.stdout"

- name: Show kibana_system password
  debug:
    msg: "{{ kibana_pass_output.stdout }}"
  when: "'password:' in kibana_pass_output.stdout"
